### PR TITLE
Tutorial: How to Create Grafana Alerts from Flux Queries

### PR DESCRIPTION
**Pull request by zuchka**
a new tutorial: How to Create Grafana Alerts from Flux Queries

written by community member Grant Pinkos.

### CODE REVIEW

**Comment by Eve832** [comment]
Hi Matt. Thanks for this!! Some quick thoughts:
- I'm not super familiar with the formatting for the other tutorials, but we'll want to change the titles and headings to sentence-case. 
- I would like to rearrange some of the content so that we use numbered steps in a task-based format, with sections that are titled H2s or H3s, but without those being numbered. For example:
### How to create a Grafana alert when a value is above or below a set threshold
1. dfhweoith
1. sogeithoih
1. dsghaoie

I'm happy to make these edits myself. Let me know when the content is complete, and I'll cut a branch from yours

**Comment by zuchka** [comment]
@Eve832 I pushed some new commits:
- fixed some typos
- changed the header casing
- add numbered steps inside each header section

I think this is just about ready to go. Can you review? I'm super excited to see this one get published! ❤️  🚀

**Comment by zuchka** [comment]
@Eve832 can we get this published? anything I can do to help move the piece forward? ty! ❤️

**Review by zuchka — COMMENTED** [review]
looks great!

**Pull request merged**
